import { uid } from "uid"

export const preworkoutArr = [
  {
    id: uid(),
    name: "Creatine Monohydrate",
    img: [
      "https://rysesupps.com/cdn/shop/files/btl_creatine_1_500x.png?v=1693981981",
    ],
    displayimg: [
      "https://rysesupps.com/cdn/shop/files/btl_creatine_1_500x.png?v=1693981981",
      "https://rysesupps.com/cdn/shop/files/btl_creatine_3_x500.png?v=1693981985",
      "https://rysesupps.com/cdn/shop/files/btl_creatine_2_x500.png?v=1693981985",
    ],
    flavour: ["Unflavoured"],
    price: ["2000"],
    desc: `Creatine is stored in the muscle as creatine phosphate. Those familiar know ATP, cellular energy, is adenosine triphosphate. There’s something special about those phosphates. When they are clipped off the parent molecule, they release a ton of energy. The cell is able to harvest this energy and put it to work. In the muscle, this powers muscle contractions.`,
    quantity: 1,
    rating: 5,
    weight: ["500gm"],
    type: "Supplement",
    category: "creatine",
  },
  {
    id: uid(),
    name: "Stim Daddy",
    img: [
      "https://rysesupps.com/cdn/shop/files/pbo_br_1_500x.png?v=1694782066",
      "https://rysesupps.com/cdn/shop/files/pbo_cw_1_500x.png?v=1694782066 ",
    ],
    displayimg: [
      "https://rysesupps.com/cdn/shop/files/pbo_br_1_500x.png?v=1694782066",
      "https://rysesupps.com/cdn/shop/files/pbo_cw_1_500x.png?v=1694782066 ",
      "https://rysesupps.com/cdn/shop/files/sfp-nd-sd.svg?v=1694796906",
    ],
    flavour: ["Blue Raspberry", "Candy Watermelon"],
    price: ["5000"],
    desc: `Ryse presents the follow up to Noel Deyzel’s Signature Series with Stim Daddy High-Stimulant Pre-Workout. The father of stims has arrived and packs a punch like never before with 21+ grams of active ingredients designed specifically for intense energy, lasered in focus, and euphoric mood. If you’re a stimulant junkie, look no further, but don’t say we didn’t warn you first.`,
    quantity: 1,
    rating: 5,
    weight: ["500gm"],
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "Pump Daddy V2",
    img: [
      "https://rysesupps.com/cdn/shop/files/pbo_new_br_1_500x.png?v=1694793315",
      "https://rysesupps.com/cdn/shop/files/pbo_new_cw_1_500x.png?v=1694793323",
    ],
    displayimg: [
      "https://rysesupps.com/cdn/shop/files/pbo_new_br_1_500x.png?v=1694793315",
      "https://rysesupps.com/cdn/shop/files/pbo_new_cw_1_500x.png?v=1694793323",
      "https://rysesupps.com/cdn/shop/files/sfp-pd2-cw.svg?v=1694797041",
    ],
    flavour: ["Blue Raspberry", "Candy Watermelon"],
    price: ["5000"],
    desc: `Pump Daddy Non-Stim Pre-Workout is everything you love about increased pumps and performance just without the caffeine. Late nights workouts, taking a break from caffeine, or stacked with your favorite pre-workout, the versatility is endless.`,
    quantity: 1,
    rating: 5,
    weight: ["500gm"],
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "Godzilla Pre-Workout",
    img: [
      "https://rysesupps.com/cdn/shop/files/pbo_pp_1_500x.png?v=1693970696",
      "https://rysesupps.com/cdn/shop/files/pbo_1_500x.png?v=1693970696",
      "https://rysesupps.com/cdn/shop/files/blackberrylemonade_1_0a448f9c-3bd7-4789-be0c-a39df92d8b20_500x.png?v=1693970696",
      "https://rysesupps.com/cdn/shop/files/strawberrykiwi_1_500x.png?v=1693970037",
    ],
    displayimg: [
      "https://rysesupps.com/cdn/shop/files/pbo_pp_1_500x.png?v=1693970696",
      "https://rysesupps.com/cdn/shop/files/pbo_1_500x.png?v=1693970696",
      "https://rysesupps.com/cdn/shop/files/blackberrylemonade_1_0a448f9c-3bd7-4789-be0c-a39df92d8b20_500x.png?v=1693970696",
      "https://rysesupps.com/cdn/shop/files/strawberrykiwi_1_500x.png?v=1693970037",
      "https://rysesupps.com/cdn/shop/files/ryse-godzillapre-sfp-sk.png?v=1660327032",
    ],
    flavour: [
      "Passion Pineapple",
      "Godzilla Monsterberry Lime",
      "Blackberry Lemonade",
      "Strawberry Kiwi",
    ],
    price: ["5000"],
    desc: `Packing a massive 40g serving size, this giant delivers city-crushing pumps, razor sharp focus & long-lasting explosive energy. Loaded with 12 ingredients, 5 clinically studied trademarks and a delicious blast of flavor, your new favorite pre-workout is ready for battle.`,
    quantity: 1,
    rating: 5,
    weight: ["500gm"],
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "Element Pre-Workout",
    img: [
      "https://rysesupps.com/cdn/shop/files/btl_element_so_1_500x.png?v=1693981863",
      "https://rysesupps.com/cdn/shop/files/btl_ringpop_bluerazz_1_500x.png?v=1693981863",
      "https://rysesupps.com/cdn/shop/files/btl_baja_1_500x.png?v=1693981863",
    ],
    displayimg: [
      "https://rysesupps.com/cdn/shop/files/btl_element_so_1_500x.png?v=1693981863",
      "https://rysesupps.com/cdn/shop/files/btl_ringpop_bluerazz_1_500x.png?v=1693981863",
      "https://rysesupps.com/cdn/shop/files/btl_baja_1_500x.png?v=1693981863",
      "https://rysesupps.com/cdn/shop/files/pre-baja-nfp.png?v=1691428537",
    ],
    flavour: [
      "SunnyD Orange Strawberry",
      "Blue Raspberry Ring Pop",
      "Baja Cooler",
    ],
    price: ["5000"],
    desc: `Everything you need and nothing you don't. Now introducing the RYSE Element Series Pre-Workout. This pre-workout was designed with daily use in mind, and to bridge the gap between those high stimulant days. However, we did not compromise and this pre-workout delivers with clinical dosages and versatility.`,
    quantity: 1,
    rating: 5,
    weight: ["500gm"],
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "Blackout: Pre-Workout",
    img: [
      "https://rysesupps.com/cdn/shop/files/ryse_2_1_white_314aca74-a2f6-42c8-a8c9-2ede17c87548_500x.png?v=1694017852",
      "https://rysesupps.com/cdn/shop/files/baja_burst_1_500x.png?v=1694017852",
      "https://rysesupps.com/cdn/shop/files/tigersblood_1_5ceceae2-977d-46b2-8b09-4e85dfb97182_500x.png?v=1694017852",
      "https://rysesupps.com/cdn/shop/files/mangoextreme_1_500x.png?v=1694017852",
    ],
    displayimg: [
      "https://rysesupps.com/cdn/shop/files/ryse_2_1_white_314aca74-a2f6-42c8-a8c9-2ede17c87548_500x.png?v=1694017852",
      "https://rysesupps.com/cdn/shop/files/baja_burst_1_500x.png?v=1694017852",
      "https://rysesupps.com/cdn/shop/files/tigersblood_1_5ceceae2-977d-46b2-8b09-4e85dfb97182_500x.png?v=1694017852",
      "https://rysesupps.com/cdn/shop/files/mangoextreme_1_500x.png?v=1694017852",
      "https://rysesupps.com/cdn/shop/files/nfp-pre-mango.jpg?v=1666310520",
    ],
    flavour: [
      "SunnyD Tangy Original",
      "Baja Burst",
      "Tigers Blood",
      "Mango Extreme",
    ],
    price: ["5000"],
    desc: `Supercharge your most grueling workouts with the all new high performance PROJECT BLACKOUT PRE from RYSE. Packed with our high-stimulant performance matrix and patented pump formula, RYSE PROJECT BLACKOUT will satisfy even the most advanced hardcore athlete.`,
    quantity: 1,
    rating: 5,
    weight: ["500gm"],
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "MuscleBlaze Pre Workout WrathX",
    img: [
      "https://img7.hkrtcdn.com/25632/prd_2563196-MuscleBlaze-Pre-Workout-WrathX-0.66-lb-Voodoo-Black_o.jpg",
      "https://img7.hkrtcdn.com/25632/prd_2563196-MuscleBlaze-Pre-Workout-WrathX-0.66-lb-Voodoo-Black_o.jpg",
    ],
    displayimg: [
      "https://img7.hkrtcdn.com/25632/prd_2563196-MuscleBlaze-Pre-Workout-WrathX-0.66-lb-Voodoo-Black_o.jpg",
      "https://img7.hkrtcdn.com/25632/prd_2563196-MuscleBlaze-Pre-Workout-WrathX-0.66-lb-Voodoo-Black_o.jpg",
      "https://img4.hkrtcdn.com/25633/bnr_2563222_o.jpg",
    ],
    flavour: [" Fruit Fury", "Voodoo Black"],
    price: ["799", "1499"],
    desc: `Summon your inner beast with the spellbinding taste of the new flavours of WrathX
The all new MuscleBlaze® WrathX  is the ultimate pre workout mix to give you an advanced level of performance that you have never witnessed before
WrathX is powered with a unique combination of Caffeine, EnXtra and Theanine for explosive energy for every workout
With added L- Citrulline, L-Arginine to give you monstrous muscle pump for desired vasodilation
A mighty mix of Taurine, Tyrosine and Choline along with Caffeine for laser sharp mental focus and athletic performance`,
    quantity: 1,
    rating: 5,
    weight: ["300gm", "500gm"],
    uuserSelected: null,
    userSelectedWeight: null,
    userSelectedPrice: null,
    userSelectedSubtotal: null,
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "MuscleBlaze PRE Workout Xtreme",
    img: [
      "https://img5.hkrtcdn.com/22100/prd_2209934-MuscleBlaze-PRE-Workout-200-Xtreme-0.22-lb-BerryBolt_o.jpg",
      "https://img4.hkrtcdn.com/28162/prd_2816113-MuscleBlaze-PRE-Workout-200-Xtreme-0.22-lb-Fruit-Punch_o.jpg",
      "https://img4.hkrtcdn.com/29738/prd_2973763-MuscleBlaze-PRE-Workout-200-Xtreme-0.44-lb-Rola-Cola_o.jpg",
    ],
    displayimg: [
      "https://img5.hkrtcdn.com/22100/prd_2209934-MuscleBlaze-PRE-Workout-200-Xtreme-0.22-lb-BerryBolt_o.jpg",
      "https://img4.hkrtcdn.com/28162/prd_2816113-MuscleBlaze-PRE-Workout-200-Xtreme-0.22-lb-Fruit-Punch_o.jpg",
      "https://img4.hkrtcdn.com/29738/prd_2973763-MuscleBlaze-PRE-Workout-200-Xtreme-0.44-lb-Rola-Cola_o.jpg",
      "https://img6.hkrtcdn.com/29739/bnr_2973805_o.jpg",
    ],
    flavour: ["Berry Bolt", "Fruit Punch", "Rola Cola"],
    price: ["500", "999"],
    desc: `MuscleBlaze Pre-Workout 200 Xtreme is a potent Pre-Workout formula that is crafted to let your body prepare itself for intense workouts. In just a single serving of this product, you’ll feel energized and focused enough to perform heavy-duty exercises. This Pre-Workout fuel is packed with 200mg Caffeine + 200mg Theanine to to give you instant and sustained release of energy. This powerful Pre-Workout aid is enriched with L-citrulline to enhance pump and Beta Alanine to add to the endurance. It is available in exhilarating Rola Cola flavour to let you have a refreshing experience before workouts.`,
    quantity: 1,
    rating: 5,
    weight: ["100g", "200gm"],
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "MuscleBlaze PRE Workout 300",
    img: [
      "https://img8.hkrtcdn.com/30066/prd_3006517-MuscleBlaze-PRE-Workout-300-0.55-lb-Fruit-Punch_o.jpg",
      "https://img4.hkrtcdn.com/9952/prd_995103-MuscleBlaze-PRE-Workout-300-0.55-lb-Green-Appple_o.jpg",
      "https://img4.hkrtcdn.com/11319/prd_1131813-MuscleBlaze-PRE-Workout-300-0.27-lb-Fruit-Punch_o.jpg",
    ],
    displayimg: [
      "https://img8.hkrtcdn.com/30066/prd_3006517-MuscleBlaze-PRE-Workout-300-0.55-lb-Fruit-Punch_o.jpg",
      "https://img4.hkrtcdn.com/9952/prd_995103-MuscleBlaze-PRE-Workout-300-0.55-lb-Green-Appple_o.jpg",
      "https://img4.hkrtcdn.com/11319/prd_1131813-MuscleBlaze-PRE-Workout-300-0.27-lb-Fruit-Punch_o.jpg",
      "https://img4.hkrtcdn.com/11319/bnr_1131821_o.jpg",
    ],
    flavour: ["Fruit Punch", "Green Apple", "Melon Twist"],
    price: ["1500", "2000"],
    desc: `Everything you need and nothing you don't. Now introducing the RYSE Element Series Pre-Workout. This pre-workout was designed with daily use in mind, and to bridge the gap between those high stimulant days. However, we did not compromise and this pre-workout delivers with clinical dosages and versatility.`,
    quantity: 1,
    rating: 5,
    weight: ["100g", "200g"],
    type: "Supplement",
    category: "preworkout",
  },

  {
    id: uid(),
    name: " Loaded Protein",
    img: [
      "https://rysesupps.com/cdn/shop/files/2lb_bbm_1_500x.png?v=1693982727",
      "https://rysesupps.com/cdn/shop/files/protein_1_500x.png?v=1694285122",
      "https://rysesupps.com/cdn/shop/files/2lb_pbc_1_500x.png?v=1694285122",
      "https://rysesupps.com/cdn/shop/files/ryse_2_4_500x.png?v=1694285122",
    ],
    displayimg: [
      "https://rysesupps.com/cdn/shop/files/2lb_bbm_1_500x.png?v=1693982727",
      "https://rysesupps.com/cdn/shop/files/protein_1_500x.png?v=1694285122",
      "https://rysesupps.com/cdn/shop/files/2lb_pbc_1_500x.png?v=1694285122",
      "https://rysesupps.com/cdn/shop/files/ryse_2_4_500x.png?v=1694285122",
      "https://rysesupps.com/cdn/shop/files/nfp-ct.png?v=1666314056",
    ],
    flavour: [
      "Blueberry Muffin",
      "Cinnamon Toast",
      "Chocolate Peanut Butter Cup",
      "Chocolate Cookie Blast",
    ],
    price: ["5000", "7000"],
    desc: `RYSE LOADED PROTEIN Combines premium Ingredients with Added Benefits while Simultaneously Bringing Incredible 5 star reviewed flavors to the table! There is no reason you can't have the added benefits of a high quality protein formula without sacrificing taste. Let RYSE LOADED PROTEIN show you the difference!`,
    quantity: 1,
    rating: 5,
    weight: ["1kg", "2kg"],
    type: "Supplement",
    category: "whey-protein",
  },

  {
    id: uid(),
    name: "MuscleBlaze Biozyme Performance Whey",
    img: [
      "https://img3.hkrtcdn.com/27426/prd_2742542-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Rich-Chocolate_o.jpg",
      "https://img1.hkrtcdn.com/18582/prd_1858120-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Choco-Banana-Smoothie_o.jpg",
      "https://img5.hkrtcdn.com/16990/prd_1698904-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Chocolate-Cake_o.jpg",
    ],
    displayimg: [
      "https://img3.hkrtcdn.com/27426/prd_2742542-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Rich-Chocolate_o.jpg",
      "https://img1.hkrtcdn.com/18582/prd_1858120-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Choco-Banana-Smoothie_o.jpg",
      "https://img5.hkrtcdn.com/16990/prd_1698904-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Chocolate-Cake_o.jpg",
      "https://img4.hkrtcdn.com/15599/bnr_1559807_o.jpg",
    ],
    flavour: [
      "Blueberry Muffin",
      "Cinnamon Toast",
      "Chocolate Peanut Butter Cup",
      
    ],
    price: ["3000", "4500"],
    desc: `RYSE LOADED PROTEIN Combines premium Ingredients with Added Benefits while Simultaneously Bringing Incredible 5 star reviewed flavors to the table! There is no reason you can't have the added benefits of a high quality protein formula without sacrificing taste. Let RYSE LOADED PROTEIN show you the difference!`,
    quantity: 1,
    rating: 5,
    weight: ["1kg", "2kg"],
    type: "Supplement",
    category: "whey-protein",
  },
  {
    id: uid(),
    name: "KNK ® Weight Lifting Rod",
    brand: "KNK",
    img: [
      "https://m.media-amazon.com/images/I/31fVvVytXrL.jpg",
      "https://m.media-amazon.com/images/I/21w5387zBJL.jpg",
      "https://m.media-amazon.com/images/I/41s5MVIeTJL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/41UM2vjWNeS.jpg",
    ],
    color: ["Crome Plated"],
    price: ["5000"],
    desc: `Chrome Plated Steel Gym Rod, Plain Rod, Weight Lifting Bar |Gym Bar |Gym
  Rod | Rods Combo |Fitness for Exercise, Fitness & Home Gym (19MM)
  (3-FT-STRAIGHT-ROD)
  `,
    quantity: 1,
    rating: 5,
    weight: ["1kg"],
    type: "equipment",
    category: "barbell",
  },
  {
    id: uid(),
    name: "Kore barbell",
    brand: "Kore",
    img: [
      "https://m.media-amazon.com/images/I/71WsD8tv2JL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71Xaz5wHxfL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71TI3ykigRL._SX679_.jpg",
    ],
    color: ["Crome Plated"],
    price: ["790"],

    desc: `Kore 26 mm Crome Plated barbell (3 feet, 4 feet, 5 feet, 6 feet, 7 feet) Weight Lifting Bar with 2 Locks`,
    quantity: 1,
    rating: 5,
    weight: ["1kg"],
    type: "equipment",
    category: "barbell",
  },
]
