import { uid } from "uid"

export const preworkoutArr = [
  {
    id: uid(),
    name: "Stim Daddy",
    img: [
      "https://rysesupps.com/cdn/shop/files/pbo_br_1_500x.png?v=1694782066",
    ],
    flavour: ["Blue Raspberry", "Candy Watermelon"],
    price: "5000",
    desc: `Ryse presents the follow up to Noel Deyzel’s Signature Series with Stim Daddy High-Stimulant Pre-Workout. The father of stims has arrived and packs a punch like never before with 21+ grams of active ingredients designed specifically for intense energy, lasered in focus, and euphoric mood. If you’re a stimulant junkie, look no further, but don’t say we didn’t warn you first.`,
    quantity: 1,
    subtotal: 2000,
    rating: 5,
    weight: "500gm",
    userSelected: null,
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "Creatine Monohydrate",
    img: [
      "https://rysesupps.com/cdn/shop/files/btl_creatine_1_500x.png?v=1693981981",
      "https://rysesupps.com/cdn/shop/files/btl_creatine_3_x500.png?v=1693981985",
      "https://rysesupps.com/cdn/shop/files/btl_creatine_2_x500.png?v=1693981985",
    ],
    flavour: ["Unflavoured"],
    price: "5000",
    desc: `Creatine is stored in the muscle as creatine phosphate. Those familiar know ATP, cellular energy, is adenosine triphosphate. There’s something special about those phosphates. When they are clipped off the parent molecule, they release a ton of energy. The cell is able to harvest this energy and put it to work. In the muscle, this powers muscle contractions.`,
    quantity: 1,
    subtotal: 2000,
    rating: 5,
    weight: "500gm",
    userSelected: null,
    type: "Supplement",
    category: "creatine",
  },
  {
    id: uid(),
    name: "Stim Daddy",
    img: [
      "https://rysesupps.com/cdn/shop/files/pbo_br_1_500x.png?v=1694782066",
    ],
    flavour: ["Blue Raspberry", "Candy Watermelon"],
    price: "5000",
    desc: `Ryse presents the follow up to Noel Deyzel’s Signature Series with Stim Daddy High-Stimulant Pre-Workout. The father of stims has arrived and packs a punch like never before with 21+ grams of active ingredients designed specifically for intense energy, lasered in focus, and euphoric mood. If you’re a stimulant junkie, look no further, but don’t say we didn’t warn you first.`,
    quantity: 1,
    subtotal: 2000,
    rating: 5,
    weight: "500gm",
    userSelected: null,
    type: "Supplement",
    category: "preworkout",
  },
  {
    id: uid(),
    name: "Creatine Monohydrate",
    img: [
      "https://rysesupps.com/cdn/shop/files/btl_creatine_1_500x.png?v=1693981981",
      "https://rysesupps.com/cdn/shop/files/btl_creatine_3_x500.png?v=1693981985",
      "https://rysesupps.com/cdn/shop/files/btl_creatine_2_x500.png?v=1693981985",
    ],
    flavour: ["Unflavoured"],
    price: "5000",
    desc: `Creatine is stored in the muscle as creatine phosphate. Those familiar know ATP, cellular energy, is adenosine triphosphate. There’s something special about those phosphates. When they are clipped off the parent molecule, they release a ton of energy. The cell is able to harvest this energy and put it to work. In the muscle, this powers muscle contractions.`,
    quantity: 1,
    subtotal: 2000,
    rating: 5,
    weight: "500gm",
    userSelected: null,
    type: "Supplement",
    category: "creatine",
  },
  {
    id: uid(),
    name: "Creatine Monohydrate",
    brand: "Ryse",
    img: [
      "https://rysesupps.com/cdn/shop/files/btl_creatine_1_500x.png?v=1693981981",
      "https://rysesupps.com/cdn/shop/files/btl_creatine_3_x500.png?v=1693981985",
      "https://rysesupps.com/cdn/shop/files/btl_creatine_2_x500.png?v=1693981985",
    ],
    flavour: ["Unflavoured"],
    price: "5000",
    desc: `Creatine is stored in the muscle as creatine phosphate. Those familiar know ATP, cellular energy, is adenosine triphosphate. There’s something special about those phosphates. When they are clipped off the parent molecule, they release a ton of energy. The cell is able to harvest this energy and put it to work. In the muscle, this powers muscle contractions.`,
    quantity: 1,
    subtotal: 2000,
    rating: 5,
    weight: "500gm",
    userSelected: null,
    type: "Supplement",
    category: "creatine",
  },
  {
    id: uid(),
    name: "KNK ® Weight Lifting Rod",
    brand: "KNK",
    img: [
      "https://m.media-amazon.com/images/I/31fVvVytXrL.jpg",
      "https://m.media-amazon.com/images/I/21w5387zBJL.jpg",
      "https://m.media-amazon.com/images/I/41s5MVIeTJL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/41UM2vjWNeS.jpg",
    ],
    color: ["Crome Plated"],
    price: "5000",
    desc: `Chrome Plated Steel Gym Rod, Plain Rod, Weight Lifting Bar |Gym Bar |Gym
  Rod | Rods Combo |Fitness for Exercise, Fitness & Home Gym (19MM)
  (3-FT-STRAIGHT-ROD)
  `,
    quantity: 1,
    subtotal: 5000,
    rating: 5,
    weight: "1kg",
    userSelected: null,
    type: "equipment",
    category: "barbell",
  },
]
